# Mapping between version and SkyPilot commit. The CI will update the catalogs
# for all versions listed here. We keep older versions for backward
# compatibility.
version_commit:
  # This commit should be fixed, as any newer commit will be fetching v6
  # catalogs
  v7: latest
