name: "update-cudo-catalog"
on:
  schedule:
    - cron:  '30 */7 * * *'    # Every 7 hours (as per _PULL_FREQUENCY_HOURS in cudo_catalog.py)
  workflow_dispatch:

jobs:
  update_cudo_catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Clone SkyPilot repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: skypilot-org/skypilot
          path: sky
      - name: Clone Catalog repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: catalogs
          token: ${{ secrets.GH_ACTION_PAT }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          python-version: "3.11"
      - name: Install dependencies
        run: |
          uv venv --seed ~/catalogs-venv
          source ~/catalogs-venv/bin/activate
          cd sky
          uv pip install ".[cudo]"

      - name: Run fetch_cudo
        id: fetch_catalogs
        run: |
          mkdir -p ~/.config/cudo
          echo "${{ secrets.CUDO_CREDENTIAL_CONFIG }}" > ~/.config/cudo/cudo.yml
          source ~/catalogs-venv/bin/activate
          versions=$(cat catalogs/.metadata.yml | yq -r '.version_commit | keys[]')
          for version in $versions; do
            commit_hash=$(cat catalogs/.metadata.yml | yq -r ".version_commit.$version")
            cd sky
            if [ "$commit_hash" == "latest" ]; then
              commit_hash=$(git rev-parse origin/master)
            fi
            git checkout $commit_hash
            uv pip install ".[cudo]"
            cd -
            mkdir -p catalogs/catalogs/$version
            cd catalogs/catalogs/$version
            python -m sky.catalog.data_fetchers.fetch_cudo
            cd -
          done

      - name: Commit catalog
        run: |
          versions=$(cat catalogs/.metadata.yml | yq -r '.version_commit | keys[]' | tr '\n' ', ')
          cd catalogs
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m"[Bot] Update Cudo catalog $versions (scheduled at $(date))" || { echo "No changes to commit" && exit 0; }
          git fetch origin
          git rebase origin/master
          git push