name: "update-aws-catalog"
on:
  schedule:
    - cron:  '00 */7 * * *'    # Every 7 hours (coprimes with 24)
    # The frequency can be tuned for the trade-off between
    # freshness of the price and github action cost/user downloading
    # overhead of the update.
    # _UPDATE_FREQUENCY_HOURS in `aws_catalog.py` need to be updated
    # accordingly, if this is changed.
  workflow_dispatch:

jobs:
  update_aws_catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Clone SkyPilot repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: skypilot-org/skypilot
          path: sky
      - name: Clone Catalog repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: catalogs
          token: ${{ secrets.GH_ACTION_PAT }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          python-version: "3.10"
      - name: Run fetch_aws
        id: fetch_catalogs
        run: |
          uv venv --seed ~/catalogs-venv
          source ~/catalogs-venv/bin/activate
          versions=$(cat catalogs/.metadata.yml | yq -r '.version_commit | keys[]')
          # Loop over all versions and commit hashes
          for version in $versions; do
            # Find commit hash for the version
            commit_hash=$(cat catalogs/.metadata.yml | yq -r ".version_commit.$version")
            cd sky
            if [ "$commit_hash" == "latest" ]; then
              # Find the latest commit of the remote SkyPilot repo
              commit_hash=$(git rev-parse origin/master)
            fi
            git checkout $commit_hash
            uv pip install ".[aws]"
            cd -
            echo "Fetching AWS catalog for version $version, SkyPilot commit hash $commit_hash"
            mkdir -p catalogs/catalogs/$version
            cd catalogs/catalogs/$version
            # Uses --check-all-regions-enabled-for-account to ensure that the catalog fetched has all regions, otherwise fail the job.
            python -m sky.catalog.data_fetchers.fetch_aws --no-az-mappings --check-all-regions-enabled-for-account
            cd -
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Commit catalog
        run: |
          versions=$(cat catalogs/.metadata.yml | yq -r '.version_commit | keys[]' | tr '\n' ', ')
          cd catalogs
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m"[Bot] Update AWS catalog $versions (scheduled at $(date))" || { echo "No changes to commit" && exit 0; }
          git fetch origin
          git rebase origin/master
          git push
      
